alternative_frontpage.settings:
  type: config_object
  label: 'Alternative Frontpage Settings'
  mapping:
    pages:
      type: sequence
      label: 'Front page per role'
      sequence:
        type: string
