social_group_invite.settings:
  type: config_object
  label: 'Social Group Invite Settings'
  mapping:
    invite_helper:
      type: text
      label: 'The invite helper text.'

# Extend schema with additional fields.
social_group.settings:
  type: config_object
  mapping:
    override_resend:
      type: boolean
      label: 'Override resend message status'
    invite_resend_message:
      type: text
      label: 'Invite resend message'
