block.settings.search_recommended_block:
  type: block_settings
  label: 'Search recommended block'
  mapping:
    partial_search:
      type: boolean
      label: 'Use partial search'
    total_items:
      type: integer
      label: 'Total items to display'
