field.field.profile.profile.field_profile_nick_name:
  expected_config:
    description: ''
  update_actions:
    change:
      description: |
        The nickname field allows you to hide your real names for other users (except site managers).
        If the field is empty other users will see your real names (everywhere they're displaying).
