name: Coding Standards

on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  phpstan7:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Set default PHP7.4
        run: sudo update-alternatives --set php /usr/bin/PHP7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP Stan
        run: vendor/bin/phpstan analyse -c phpstan.neon

  phpcs7:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Set default PHP7.4
        run: sudo update-alternatives --set php /usr/bin/PHP7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPCS
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
          enable_warnings: true

  phpstan8:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Set default PHP8.0
        run: sudo update-alternatives --set php /usr/bin/PHP8.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP Stan
        run: vendor/bin/phpstan analyse -c phpstan.neon

  phpcs8:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Set default PHP7.4
        run: sudo update-alternatives --set php /usr/bin/PHP8.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPCS
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
          enable_warnings: true
